"""
Purpose:
    Build the final thesis comparison figure using outputs from
    08_eval_super_resolution.py. It compares the VQGAN-decoded HR reference,
    an interpolation baseline, and the MAR latent reconstruction using shared
    0-255 intensity scaling and axial/coronal/sagittal views.

Suggested filename:
    08_make_final_sr_comparison_figure.py
"""

# Allow this copied script to be run from either the repository root or Evaluate/.
from pathlib import Path
import sys
import os

REPO_ROOT = Path(__file__).resolve().parents[1]
if str(REPO_ROOT) not in sys.path:
    sys.path.insert(0, str(REPO_ROOT))
os.chdir(REPO_ROOT)



import os
import sys

import matplotlib.pyplot as plt
import nibabel as nib
import numpy as np
from nibabel.processing import resample_from_to
from skimage.metrics import peak_signal_noise_ratio as psnr
from skimage.metrics import structural_similarity as ssim


# Inputs generated by 08_eval_super_resolution.py.
ALIGNED_GT_NIFTI_PATH = "08_eval_SR_01_HR_GroundTruth.nii.gz"
MODEL_SR_NIFTI_PATH = "08_eval_SR_03_Reconstructed.nii.gz"

OUTPUT_PLOT = "08_final_super_resolution_comparison_aligned.png"


def load_uint8_volume(path: str) -> tuple[np.ndarray, nib.Nifti1Image]:
    if not os.path.exists(path):
        print(f"Missing file: {path}")
        sys.exit(1)

    img = nib.load(path)
    data = img.get_fdata().astype(np.float32)

    # The evaluation scripts save viewable NIfTI files in 0-255 uint8 space.
    # Keep this common range for fair PSNR/SSIM instead of independently
    # min-max normalising each method.
    if data.min() >= -1.0 and data.max() <= 1.0:
        data = (np.clip(data, -1, 1) + 1.0) / 2.0 * 255.0
    else:
        data = np.clip(data, 0, 255)

    return data.astype(np.uint8), img


def make_interpolation_baseline(gt_img: nib.Nifti1Image) -> np.ndarray:
    gt_data = gt_img.get_fdata().astype(np.float32)
    gt_data = np.clip(gt_data, 0, 255)
    gt_img_u8 = nib.Nifti1Image(gt_data, gt_img.affine)

    downsample_affine = gt_img.affine.copy()
    downsample_affine[:3, :3] *= 2.0
    lr_target = (np.zeros((32, 32, 32), dtype=np.float32), downsample_affine)

    # Linear downsample approximates acquisition degradation; cubic upsample is
    # used as the traditional interpolation SR baseline.
    lr_img = resample_from_to(gt_img_u8, lr_target, order=1)
    interp_img = resample_from_to(lr_img, gt_img_u8, order=3)
    return np.clip(interp_img.get_fdata(), 0, 255).astype(np.uint8)


def choose_representative_slices(vol_uint8: np.ndarray) -> tuple[int, int, int]:
    threshold = max(10, int(np.percentile(vol_uint8, 70)))
    fg = vol_uint8 > threshold
    if fg.sum() == 0:
        return tuple(s // 2 for s in vol_uint8.shape)
    d_idx = int(np.argmax(fg.sum(axis=(1, 2))))
    h_idx = int(np.argmax(fg.sum(axis=(0, 2))))
    w_idx = int(np.argmax(fg.sum(axis=(0, 1))))
    return d_idx, h_idx, w_idx


def compute_metrics(gt: np.ndarray, pred: np.ndarray) -> tuple[float, float, float]:
    mse = np.mean((gt.astype(np.float32) - pred.astype(np.float32)) ** 2)
    val_psnr = psnr(gt, pred, data_range=255)
    val_ssim = ssim(gt, pred, data_range=255, win_size=3, channel_axis=None)
    return val_psnr, val_ssim, mse


def main() -> None:
    print(f"Loading aligned HR reference: {ALIGNED_GT_NIFTI_PATH}")
    gt_visual, gt_img = load_uint8_volume(ALIGNED_GT_NIFTI_PATH)

    print("Generating interpolation baseline: 32^3 -> 64^3")
    interp_visual = make_interpolation_baseline(gt_img)

    print(f"Loading MAR reconstruction: {MODEL_SR_NIFTI_PATH}")
    model_visual, _ = load_uint8_volume(MODEL_SR_NIFTI_PATH)

    if gt_visual.shape != model_visual.shape:
        print(f"Shape mismatch: GT={gt_visual.shape}, MAR={model_visual.shape}")
        sys.exit(1)
    if gt_visual.shape != interp_visual.shape:
        print(f"Shape mismatch: GT={gt_visual.shape}, interpolation={interp_visual.shape}")
        sys.exit(1)

    psnr_interp, ssim_interp, mse_interp = compute_metrics(gt_visual, interp_visual)
    psnr_model, ssim_model, mse_model = compute_metrics(gt_visual, model_visual)

    print("\nQuantitative comparison in shared 0-255 intensity space:")
    print(f"{'Method':<28} | {'PSNR':>9} | {'SSIM':>8} | {'MSE':>10}")
    print("-" * 64)
    print(f"{'Traditional interpolation':<28} | {psnr_interp:>6.2f} dB | {ssim_interp:>8.4f} | {mse_interp:>10.2f}")
    print(f"{'MAR latent reconstruction':<28} | {psnr_model:>6.2f} dB | {ssim_model:>8.4f} | {mse_model:>10.2f}")

    vols = [gt_visual, interp_visual, model_visual]
    row_names = [
        "HR reference\n(VQGAN decoded)",
        f"Traditional interpolation\nPSNR {psnr_interp:.2f}, SSIM {ssim_interp:.3f}",
        f"MAR reconstruction\nPSNR {psnr_model:.2f}, SSIM {ssim_model:.3f}",
    ]
    d_idx, h_idx, w_idx = choose_representative_slices(gt_visual)

    fig, axes = plt.subplots(3, 3, figsize=(12, 12))
    plt.subplots_adjust(wspace=0.08, hspace=0.30)

    for i, current_vol in enumerate(vols):
        slices = [
            current_vol[d_idx, :, :],
            current_vol[:, h_idx, :],
            current_vol[:, :, w_idx],
        ]
        for j, slc in enumerate(slices):
            ax = axes[i, j]
            ax.imshow(slc, cmap="gray", vmin=0, vmax=255, origin="lower")
            if i == 0:
                ax.set_title(["Axial", "Coronal", "Sagittal"][j], fontsize=14, fontweight="bold")
            if j == 0:
                ax.set_ylabel(row_names[i], fontsize=11, fontweight="bold", labelpad=12)
            ax.set_xticks([])
            ax.set_yticks([])

    plt.savefig(OUTPUT_PLOT, dpi=220, bbox_inches="tight")
    plt.close(fig)
    print(f"Saved comparison figure: {OUTPUT_PLOT}")


if __name__ == "__main__":
    main()
